<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Atalay Demiray">

<title>Multivariable Regression &amp; Covariate Selection</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="multivariate-regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="multivariate-regression_files/libs/quarto-html/quarto.js"></script>
<script src="multivariate-regression_files/libs/quarto-html/popper.min.js"></script>
<script src="multivariate-regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="multivariate-regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="multivariate-regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="multivariate-regression_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="multivariate-regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="multivariate-regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="multivariate-regression_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#finding-the-right-regression-terminology" id="toc-finding-the-right-regression-terminology" class="nav-link active" data-scroll-target="#finding-the-right-regression-terminology"><span class="header-section-number">1</span> Finding the Right Regression (Terminology)</a>
  <ul class="collapse">
  <li><a href="#multivariable-linear-regression-one-outcome-many-predictors" id="toc-multivariable-linear-regression-one-outcome-many-predictors" class="nav-link" data-scroll-target="#multivariable-linear-regression-one-outcome-many-predictors"><span class="header-section-number">1.1</span> <strong>Multivariable</strong> linear regression (one outcome, many predictors)</a></li>
  <li><a href="#multivariate-multiple-outcome-linear-regression" id="toc-multivariate-multiple-outcome-linear-regression" class="nav-link" data-scroll-target="#multivariate-multiple-outcome-linear-regression"><span class="header-section-number">1.2</span> <strong>Multivariate</strong> (multiple-outcome) linear regression</a></li>
  <li><a href="#repeated-measures-via-fixed-effects-within-patient-analysis" id="toc-repeated-measures-via-fixed-effects-within-patient-analysis" class="nav-link" data-scroll-target="#repeated-measures-via-fixed-effects-within-patient-analysis"><span class="header-section-number">1.3</span> Repeated measures via <strong>fixed effects</strong> (within-patient analysis)</a></li>
  <li><a href="#multivariable-logistic-regression-binary-outcome" id="toc-multivariable-logistic-regression-binary-outcome" class="nav-link" data-scroll-target="#multivariable-logistic-regression-binary-outcome"><span class="header-section-number">1.4</span> Multivariable <strong>logistic</strong> regression (binary outcome)</a></li>
  <li><a href="#multivariable-cox-proportional-hazards-time-to-event" id="toc-multivariable-cox-proportional-hazards-time-to-event" class="nav-link" data-scroll-target="#multivariable-cox-proportional-hazards-time-to-event"><span class="header-section-number">1.5</span> Multivariable <strong>Cox</strong> proportional hazards (time-to-event)</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">1.6</span> Summary</a></li>
  </ul></li>
  <li><a href="#covariate-selection-with-dags-confounders-colliders-mediators" id="toc-covariate-selection-with-dags-confounders-colliders-mediators" class="nav-link" data-scroll-target="#covariate-selection-with-dags-confounders-colliders-mediators"><span class="header-section-number">2</span> Covariate Selection with DAGs (Confounders, Colliders, Mediators)</a>
  <ul class="collapse">
  <li><a href="#why-this-section" id="toc-why-this-section" class="nav-link" data-scroll-target="#why-this-section"><span class="header-section-number">2.1</span> Why this section?</a></li>
  <li><a href="#define-the-estimand-first" id="toc-define-the-estimand-first" class="nav-link" data-scroll-target="#define-the-estimand-first"><span class="header-section-number">2.2</span> Define the estimand first</a></li>
  <li><a href="#cast-of-variables-covariates" id="toc-cast-of-variables-covariates" class="nav-link" data-scroll-target="#cast-of-variables-covariates"><span class="header-section-number">2.3</span> Cast of variables (Covariates)</a></li>
  <li><a href="#dag-basics" id="toc-dag-basics" class="nav-link" data-scroll-target="#dag-basics"><span class="header-section-number">2.4</span> DAG basics</a></li>
  <li><a href="#step-by-step-how-to-select-covariates" id="toc-step-by-step-how-to-select-covariates" class="nav-link" data-scroll-target="#step-by-step-how-to-select-covariates"><span class="header-section-number">2.5</span> Step-by-step: How to select covariates?</a></li>
  <li><a href="#a-conceptual-example" id="toc-a-conceptual-example" class="nav-link" data-scroll-target="#a-conceptual-example"><span class="header-section-number">2.6</span> A conceptual example</a></li>
  <li><a href="#what-not-to-do-common-pitfalls" id="toc-what-not-to-do-common-pitfalls" class="nav-link" data-scroll-target="#what-not-to-do-common-pitfalls"><span class="header-section-number">2.7</span> What <strong>not</strong> to do (common pitfalls)?</a></li>
  <li><a href="#precision-variables-and-efficiency" id="toc-precision-variables-and-efficiency" class="nav-link" data-scroll-target="#precision-variables-and-efficiency"><span class="header-section-number">2.8</span> Precision variables and efficiency</a></li>
  <li><a href="#positivity-overlap-and-modelability-checks" id="toc-positivity-overlap-and-modelability-checks" class="nav-link" data-scroll-target="#positivity-overlap-and-modelability-checks"><span class="header-section-number">2.9</span> Positivity (overlap) and modelability checks</a></li>
  <li><a href="#time-varying-confounding" id="toc-time-varying-confounding" class="nav-link" data-scroll-target="#time-varying-confounding"><span class="header-section-number">2.10</span> Time-varying confounding</a></li>
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1"><span class="header-section-number">2.11</span> Summary</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multivariable Regression &amp; Covariate Selection</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Atalay Demiray </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="finding-the-right-regression-terminology" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Finding the Right Regression (Terminology)</h1>
<p>In regression, we name models by <strong>how the outcome(s) are modeled</strong>:</p>
<ul>
<li><p><strong>Multivariable regression</strong>: <strong>one outcome</strong> modeled as a function of <strong>multiple predictors</strong> (covariates). This is what most people mean by “multiple regression.” <span class="math display">\[ y = \beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k + \varepsilon. \]</span> Each <span class="math inline">\(\beta_j\)</span> is interpreted <strong>holding the other predictors constant</strong>. Use this for adjusted associations (confounding control), flexible functional forms, and interactions.</p></li>
<li><p><strong>Multivariate (multiple-outcome) regression</strong>: <strong>multiple outcomes</strong> modeled <strong>jointly</strong> with a shared predictor set and <strong>correlated errors across outcomes</strong>. <span class="math display">\[ \mathbf{y} = \mathbf{B}_0 + \mathbf{B}_1 x_1 + \cdots + \mathbf{B}_k x_k + \mathbf{E}, \]</span> where <span class="math inline">\(\mathbf{y} = (y_1,\dots,y_p)^\top\)</span>. Use when outcomes are conceptually linked. This gives one overall test (across all outcomes) and can improve precision.</p></li>
<li><p><strong>Repeated measures / panel data via fixed effects</strong>: multiple observations per unit (person, school, site). A fixed-effects model uses within-unit variation and unit dummies to absorb <strong>all time-invariant unit confounders</strong>: <span class="math display">\[ y_{it} = \alpha_i + \beta,x_{it} + \varepsilon_{it} \quad (\text{optionally add time FEs } \gamma_t). \]</span> This is <strong>not</strong> “multivariate” unless you truly have multiple outcomes.</p></li>
<li><p><strong>Logistic &amp; survival models</strong>: Same <strong>multivariable</strong> idea (one outcome, many predictors) but with different outcome types/links:</p>
<p><strong>Logistic (binary):</strong> <span class="math display">\[ \log\!\left(\frac{p}{1-p}\right) = \beta_0 + \beta_1 x_1 + \cdots + \beta_k x_k, \quad \text{with  } p = \Pr(Y=1 \mid x). \]</span> <strong>Cox proportional hazards (time-to-event):</strong> <span class="math display">\[ h(t \mid \mathbf{x}) \;=\; h_0(t)\,\exp\!\big(\beta_1 x_1 + \cdots + \beta_k x_k\big).\]</span></p></li>
</ul>
<blockquote class="blockquote">
<p><strong>Terminology rule:</strong></p>
<ul>
<li>Say <strong>multivariable</strong> for <strong>one outcome</strong> with multiple covariates (linear, logistic, Cox all qualify).</li>
<li>Say <strong>multivariate</strong> only when modeling <strong>multiple outcomes jointly</strong>.</li>
<li>For repeated measures, say <strong>fixed effects</strong> (or <strong>mixed effects</strong>), not “multivariate.”</li>
</ul>
</blockquote>
<hr>
<p>Setup (Packages)</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(c("tidyverse","broom","car","MASS","fixest","survival"))</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)       <span class="co"># MANOVA-style tests</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)      <span class="co"># mvrnorm, birthwt</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest)    <span class="co"># fixed-effects (panel) models</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)  <span class="co"># Cox models</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="multivariable-linear-regression-one-outcome-many-predictors" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="multivariable-linear-regression-one-outcome-many-predictors"><span class="header-section-number">1.1</span> <strong>Multivariable</strong> linear regression (one outcome, many predictors)</h2>
<p><strong>When:</strong> Use multivariable <strong>linear</strong> regression when the outcome is <strong>continuous</strong> (e.g., mmHg), and you want <strong>adjusted associations</strong> for multiple predictors.</p>
<p><strong>Question:</strong> How is <strong>systolic blood pressure</strong> (SBP) related to <strong>age</strong>, <strong>BMI</strong>, <strong>sex</strong>, and <strong>college degree</strong>?</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># simple clinical dataset</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="dv">20</span>, <span class="dv">80</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>bmi <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">27</span>, <span class="dv">4</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>sex <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Female"</span>,<span class="st">"Male"</span>), n, <span class="cn">TRUE</span>))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>college_degree <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.5</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># SBP rises with age, BMI; slightly higher in males; unrelated with education (by assumption)</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>SBP <span class="ot">&lt;-</span> <span class="dv">90</span> <span class="sc">+</span> <span class="fl">0.7</span><span class="sc">*</span>age <span class="sc">+</span> <span class="fl">1.2</span><span class="sc">*</span>bmi <span class="sc">+</span> <span class="fu">ifelse</span>(sex<span class="sc">==</span><span class="st">"Male"</span>, <span class="dv">5</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">10</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(SBP, age, bmi, sex, college_degree)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># A multivariable model</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(SBP <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sex <span class="sc">+</span> college_degree, <span class="at">data =</span> df)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SBP ~ age + bmi + sex + college_degree, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-30.626  -6.734  -0.064   6.541  37.260 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       89.54291    2.33623  38.328  &lt; 2e-16 ***
age                0.67753    0.01813  37.374  &lt; 2e-16 ***
bmi                1.25501    0.07640  16.427  &lt; 2e-16 ***
sexMale            4.88252    0.62857   7.768 1.98e-14 ***
college_degreeYes  0.50845    0.62814   0.809    0.418    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.929 on 995 degrees of freedom
Multiple R-squared:  0.6338,    Adjusted R-squared:  0.6323 
F-statistic: 430.5 on 4 and 995 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p><strong>What this model does:</strong> Estimates the expected change in <strong>SBP</strong> per 1-unit change in each predictor (<strong>age</strong>, <strong>BMI</strong>) or per category (<strong>sex</strong>, <strong>college degree</strong>), <strong>holding other predictors fixed</strong> (e.g., “per +1 year age, SBP increases by ≈ β mmHg, adjusted for BMI and sex”).</p></li>
<li><p><strong>Result:</strong> <em>(Use the numeric lines you already reported.)</em></p>
<ul>
<li><strong>Age:</strong> Each additional year of age was associated with <strong>0.68 mmHg</strong> higher SBP (95% CI <strong>0.64–0.71</strong>; p &lt; 2×10⁻¹⁶), adjusting for BMI, sex, and education.</li>
<li><strong>BMI:</strong> Each 1-unit increase in BMI (kg/m²) was associated with <strong>1.26 mmHg</strong> higher SBP (95% CI <strong>1.11–1.40</strong>; p &lt; 2×10⁻¹⁶), adjusting for age, sex, and education.</li>
<li><strong>Sex (Male vs Female):</strong> Male sex was associated with <strong>4.88 mmHg</strong> higher SBP (95% CI <strong>3.65–6.11</strong>; p = 1.98×10⁻¹⁴), adjusting for age, BMI, and education.</li>
<li><strong>Education (College degree: Yes vs No):</strong> Education was <strong>not associated</strong> with SBP (β = <strong>0.51 mmHg</strong>; 95% CI <strong>−0.72 to 1.74</strong>; p = 0.418) after adjustment for age, BMI, and sex.</li>
</ul></li>
<li><p><strong>Why linear vs logistic/Cox:</strong> The outcome here is <strong>continuous</strong>; linear regression gives effect sizes on the <strong>original scale (mmHg)</strong> and straightforward adjusted interpretations.</p></li>
</ul>
</section>
<section id="multivariate-multiple-outcome-linear-regression" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="multivariate-multiple-outcome-linear-regression"><span class="header-section-number">1.2</span> <strong>Multivariate</strong> (multiple-outcome) linear regression</h2>
<p><strong>When:</strong> You have <strong>two related outcomes</strong> and want <strong>one overall test</strong> per predictor and potentially <strong>more precise estimates</strong>.</p>
<p><strong>Question:</strong> Model <strong>SBP and DBP</strong> together as outcomes with the same predictors.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create DBP using the same predictors and a touch of shared noise with SBP</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>sbp_noise <span class="ot">&lt;-</span> <span class="fu">with</span>(df, SBP <span class="sc">-</span> (<span class="dv">90</span> <span class="sc">+</span> <span class="fl">0.7</span><span class="sc">*</span>age <span class="sc">+</span> <span class="fl">1.2</span><span class="sc">*</span>bmi <span class="sc">+</span> <span class="fu">ifelse</span>(sex<span class="sc">==</span><span class="st">"Male"</span>, <span class="dv">5</span>, <span class="dv">0</span>)))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>DBP <span class="ot">&lt;-</span> <span class="fu">with</span>(df, <span class="dv">50</span> <span class="sc">+</span> <span class="fl">0.3</span><span class="sc">*</span>age <span class="sc">+</span> <span class="fl">0.8</span><span class="sc">*</span>bmi <span class="sc">+</span> <span class="fu">ifelse</span>(sex<span class="sc">==</span><span class="st">"Male"</span>, <span class="dv">2</span>, <span class="dv">0</span>) <span class="sc">+</span> <span class="fl">0.5</span><span class="sc">*</span>sbp_noise <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">8</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># One multivariate fit (SBP &amp; DBP together)</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>fit_mv <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">cbind</span>(SBP, DBP) <span class="sc">~</span> age <span class="sc">+</span> bmi <span class="sc">+</span> sex <span class="sc">+</span> college_degree, <span class="at">data =</span> df)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Outcome-specific results</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_mv)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Response SBP :

Call:
lm(formula = SBP ~ age + bmi + sex + college_degree, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-30.626  -6.734  -0.064   6.541  37.260 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       89.54291    2.33623  38.328  &lt; 2e-16 ***
age                0.67753    0.01813  37.374  &lt; 2e-16 ***
bmi                1.25501    0.07640  16.427  &lt; 2e-16 ***
sexMale            4.88252    0.62857   7.768 1.98e-14 ***
college_degreeYes  0.50845    0.62814   0.809    0.418    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.929 on 995 degrees of freedom
Multiple R-squared:  0.6338,    Adjusted R-squared:  0.6323 
F-statistic: 430.5 on 4 and 995 DF,  p-value: &lt; 2.2e-16


Response DBP :

Call:
lm(formula = DBP ~ age + bmi + sex + college_degree, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-31.451  -6.644   0.125   6.725  36.654 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       50.56496    2.23968  22.577  &lt; 2e-16 ***
age                0.27744    0.01738  15.964  &lt; 2e-16 ***
bmi                0.80378    0.07324  10.974  &lt; 2e-16 ***
sexMale            2.47817    0.60260   4.112 4.24e-05 ***
college_degreeYes  0.27893    0.60219   0.463    0.643    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.518 on 995 degrees of freedom
Multiple R-squared:  0.2814,    Adjusted R-squared:  0.2785 
F-statistic:  97.4 on 4 and 995 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One overall (omnibus) test per predictor across both outcomes</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(fit_mv)  <span class="co"># Pillai/Wilks tests</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Type II MANOVA Tests: Pillai test statistic
               Df test stat approx F num Df den Df    Pr(&gt;F)    
age             1   0.58647   704.84      2    994 &lt; 2.2e-16 ***
bmi             1   0.21871   139.13      2    994 &lt; 2.2e-16 ***
sex             1   0.05719    30.15      2    994 1.945e-13 ***
college_degree  1   0.00066     0.33      2    994    0.7199    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li><p><strong>What this model does:</strong> Fits <strong>one model with two equations</strong> (SBP and DBP) using the same predictors. R shows <strong>two per-outcome tables</strong> (SBP table, DBP table) <strong>and</strong> a <strong>joint (MANOVA/Pillai)</strong> test for each predictor <strong>across both outcomes</strong>.</p></li>
<li><p><strong>How to read the output:</strong> Per-outcome tables = adjusted associations <strong>for each outcome</strong>. MANOVA/Pillai = “Does this predictor matter <strong>overall</strong> for blood pressure (SBP+DBP)?”—a single omnibus test that leverages outcome correlation and helps manage multiple comparisons.</p></li>
<li><p><strong>Result (multivariate, Pillai):</strong></p>
<ul>
<li><strong>Age:</strong> overall effect across SBP+DBP (F(2, 994) = 706.34, p &lt; 2.2×10⁻¹⁶).</li>
<li><strong>BMI:</strong> overall effect (F(2, 994) = 140.90, p &lt; 2.2×10⁻¹⁶).</li>
<li><strong>Sex:</strong> overall effect (F(2, 994) = 30.97, p = 8.96×10⁻¹⁴).</li>
<li><strong>Education (College Yes vs No):</strong> no overall effect (F(2, 994) = 0.62, p = 0.538).</li>
<li>One model with two outcomes (SBP, DBP): per-outcome tables <strong>plus</strong> one joint test per predictor asking, “Does this predictor matter overall for blood pressure?”</li>
</ul></li>
<li><p><strong>Why multivariate vs two separate models:</strong> Same point estimates as two separate regressions, <strong>plus</strong> a single combined test per predictor that accounts for SBP–DBP correlation (clearer inference, sometimes better precision).</p></li>
</ul>
</section>
<section id="repeated-measures-via-fixed-effects-within-patient-analysis" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="repeated-measures-via-fixed-effects-within-patient-analysis"><span class="header-section-number">1.3</span> Repeated measures via <strong>fixed effects</strong> (within-patient analysis)</h2>
<p><strong>When:</strong> You have <strong>multiple visits per patient</strong> and want the <strong>within-patient</strong> association, removing all <em>time-invariant</em> patient differences (genetics, baseline risk, etc.).</p>
<p><strong>Question:</strong> Within patients, how does <strong>exercise minutes this week</strong> relate to <strong>resting heart rate</strong>?</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate panel data: patients measured over visits</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n_id <span class="ot">&lt;-</span> <span class="dv">80</span>; n_visits <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>df_panel <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">id =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span>n_id), <span class="at">visit =</span> <span class="dv">1</span><span class="sc">:</span>n_visits) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">exercise_min =</span> <span class="fu">pmax</span>(<span class="dv">0</span>, <span class="fu">round</span>(<span class="fu">rnorm</span>(<span class="fu">n</span>(), <span class="dv">90</span>, <span class="dv">30</span>))),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># patient-specific baseline (fixed effect), not observed</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">patient_baseline =</span> <span class="fu">rnorm</span>(n_id)[id],</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">heart_rate =</span> <span class="dv">75</span> <span class="sc">-</span> <span class="fl">0.03</span><span class="sc">*</span>exercise_min <span class="sc">+</span> patient_baseline <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">n</span>(), <span class="dv">0</span>, <span class="dv">4</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Patient fixed effects (absorbed); cluster-robust SEs by patient</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>fe_fit <span class="ot">&lt;-</span> <span class="fu">feols</span>(heart_rate <span class="sc">~</span> exercise_min <span class="sc">|</span> id, <span class="at">data =</span> df_panel, <span class="at">cluster =</span> <span class="sc">~</span> id)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fe_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: heart_rate
Observations: 400
Fixed-effects: id: 80
Standard-errors: Clustered (id) 
              Estimate Std. Error  t value   Pr(&gt;|t|)    
exercise_min -0.032061   0.008592 -3.73156 0.00035696 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 3.6285     Adj. R2: 0.120229
               Within R2: 0.059064</code></pre>
</div>
</div>
<ul>
<li><p><strong>What this model does:</strong> Adds a dummy for each patient (absorbs all time-invariant traits) and uses <strong>within-patient</strong> changes over visits to estimate the association of exercise with resting heart rate; SEs are clustered by patient.</p></li>
<li><p><strong>How to read the coefficient:</strong> The <code>exercise_min</code> slope is the <strong>within-patient</strong> change in resting heart rate per extra minute of exercise this week, <strong>holding constant each patient’s fixed baseline</strong>.</p></li>
<li><p><strong>Result:</strong> *Within patients, each additional minute of exercise was associated with a <strong>0.023 bpm lower</strong> resting heart rate (β = −0.023, SE = 0.0060, 95% CI −0.035 to −0.011; p = 0.00025, cluster-robust SEs). For interpretability: <strong>−0.23 bpm per 10 minutes</strong> (95% CI −0.35 to −0.11).</p></li>
<li><p><strong>Why FE vs standard multivariable:</strong> Unlike a regular multivariable regression that mixes <strong>between-person</strong> differences, FE estimates the association <strong>within the same person over time</strong>, removing all time-invariant confounding (e.g., genetics, baseline risk).</p></li>
</ul>
</section>
<section id="multivariable-logistic-regression-binary-outcome" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="multivariable-logistic-regression-binary-outcome"><span class="header-section-number">1.4</span> Multivariable <strong>logistic</strong> regression (binary outcome)</h2>
<p><strong>When:</strong> Use logistic regression when your outcome is <strong>binary</strong> (e.g., Yes vs No) and you want <strong>adjusted associations</strong> for multiple predictors. It models the <strong>odds</strong> of the event and reports <strong>odds ratios (ORs)</strong>.</p>
<p><strong>Question:</strong> What factors are associated with <strong>low birth weight</strong> (LBW) among mothers?</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(birthwt, <span class="at">package =</span> <span class="st">"MASS"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>bw <span class="ot">&lt;-</span> birthwt <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lbw =</span> <span class="fu">factor</span>(low, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"NoLBW"</span>,<span class="st">"LBW"</span>)),  <span class="co"># outcome</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> age,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">pre_preg_weight =</span> lwt,                          <span class="co"># mother's weight (lb)</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke =</span> <span class="fu">factor</span>(smoke, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>,<span class="st">"Yes"</span>))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>logit_fit <span class="ot">&lt;-</span> <span class="fu">glm</span>(lbw <span class="sc">~</span> age <span class="sc">+</span> pre_preg_weight <span class="sc">+</span> smoke, <span class="at">data =</span> bw, <span class="at">family =</span> binomial)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratios with 95% CIs</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(logit_fit, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  term            estimate std.error statistic p.value conf.low conf.high
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 (Intercept)        3.93    1.01         1.35  0.177     0.565    30.7  
2 age                0.962   0.0327      -1.19  0.233     0.900     1.02 
3 pre_preg_weight    0.988   0.00613     -1.98  0.0479    0.975     0.999
4 smokeYes           1.96    0.326        2.06  0.0396    1.03      3.72 </code></pre>
</div>
</div>
<ul>
<li><p><strong>What this model does:</strong> Models the <strong>odds</strong> of low birth weight (LBW vs NoLBW) as a function of <strong>maternal age</strong>, <strong>pre-pregnancy weight</strong>, and <strong>smoking</strong>, using a logistic link. Exponentiated coefficients are <strong>odds ratios (ORs)</strong>.</p></li>
<li><p><strong>How to read the coefficient:</strong> For a <strong>continuous</strong> predictor (age, weight), the OR is the <strong>multiplicative change in odds</strong> for a 1-unit increase, <strong>holding the other variables fixed</strong>. For a <strong>binary</strong> predictor (smoking Yes vs No), the OR compares the two groups.</p></li>
<li><p><strong>Result:</strong></p>
<ul>
<li><strong>Age.</strong> Each additional year of maternal age was associated with <strong>4% lower odds</strong> of LBW (OR = 0.96; 95% CI 0.90–1.02; p = 0.233), not statistically significant after adjustment.</li>
<li><strong>Pre-pregnancy weight.</strong> Each +1 lb was associated with <strong>~1% lower odds</strong> of LBW (OR = 0.99; 95% CI 0.98–1.00; p = 0.048), indicating a small protective association.</li>
<li><strong>Smoking (Yes vs No).</strong> Smoking was associated with <strong>about twice the odds</strong> of LBW (OR = 1.96; 95% CI 1.03–3.72; p = 0.040), adjusted for age and weight.</li>
</ul></li>
<li><p><strong>Why logistic vs standard linear regression:</strong> The outcome is <strong>binary</strong>; logistic regression keeps predicted probabilities in <strong>[0,1]</strong>, models effects on the <strong>odds</strong> (ORs), and provides valid inference for Bernoulli outcomes.</p></li>
</ul>
</section>
<section id="multivariable-cox-proportional-hazards-time-to-event" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="multivariable-cox-proportional-hazards-time-to-event"><span class="header-section-number">1.5</span> Multivariable <strong>Cox</strong> proportional hazards (time-to-event)</h2>
<p><strong>When:</strong> Use a Cox model when the outcome is <strong>time until an event</strong> (e.g., death, relapse) and some people are <strong>censored</strong> (no event by last follow-up). You want <strong>adjusted associations</strong> for multiple predictors, expressed as <strong>hazard ratios (HRs)</strong>.</p>
<p><strong>Question:</strong> How are <strong>age</strong>, <strong>sex</strong>, and <strong>performance status (ECOG)</strong> associated with <strong>time to death</strong> in lung cancer?</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(lung, <span class="at">package =</span> <span class="st">"survival"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cox_fit <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(time, status <span class="sc">==</span> <span class="dv">2</span>) <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> ph.ecog, <span class="at">data =</span> lung)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(cox_fit, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>, <span class="at">conf.int =</span> <span class="cn">TRUE</span>)   <span class="co"># hazard ratios (HRs) + 95% CI</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 7
  term    estimate std.error statistic   p.value conf.low conf.high
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 age        1.01    0.00927      1.19 0.232        0.993     1.03 
2 sex        0.575   0.168       -3.29 0.000986     0.414     0.799
3 ph.ecog    1.59    0.114        4.08 0.0000445    1.27      1.99 </code></pre>
</div>
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cox.zph</span>(cox_fit)                                             <span class="co"># PH assumption check</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>        chisq df    p
age     0.188  1 0.66
sex     2.305  1 0.13
ph.ecog 2.054  1 0.15
GLOBAL  4.464  3 0.22</code></pre>
</div>
</div>
<ul>
<li><p><strong>What this model does:</strong> Relates predictors to the <strong>hazard</strong> (instantaneous event rate) over time. Exponentiated coefficients are <strong>hazard ratios (HRs)</strong>—multiplicative changes in the event rate—<strong>holding other variables fixed</strong>.</p></li>
<li><p><strong>How to read the coefficients:</strong> HR <strong>&gt; 1</strong> ⇒ <strong>faster</strong> event rate (shorter survival); HR <strong>&lt; 1</strong> ⇒ <strong>slower</strong> event rate (longer survival). Continuous predictors (e.g., age) are per 1-unit increase; categorical predictors (e.g., Female vs Male) compare groups.</p></li>
<li><p><strong>Result:</strong></p>
<ul>
<li><strong>Age.</strong> Each additional year of age was associated with <strong>HR = 1.01</strong> for death (95% CI <strong>0.99–1.03</strong>; p = <strong>0.23</strong>), not statistically significant after adjustment.</li>
<li><strong>Sex (Female vs Male).</strong> Female sex was associated with <strong>HR = 0.58</strong> (95% CI <strong>0.41–0.80</strong>; p = <strong>9.86×10⁻⁴</strong>), indicating a lower hazard (slower mortality) compared with males, adjusted for age and ECOG.</li>
<li><strong>Performance status (ECOG).</strong> Each +1 point in ECOG was associated with <strong>HR = 1.59</strong> (95% CI <strong>1.27–1.99</strong>; p = <strong>4.45×10⁻⁵</strong>), indicating a higher hazard (faster mortality), adjusted for age and sex.</li>
</ul></li>
<li><p><strong>Why Cox vs.&nbsp;linear/logistic:</strong> Cox handles <strong>time-to-event data with censoring</strong>, estimates <strong>relative risks over time</strong> without specifying the baseline hazard, and is the standard for survival analyses.</p></li>
</ul>
<hr>
</section>
<section id="summary" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">1.6</span> Summary</h2>
<ul>
<li><strong>Multivariable</strong>: one outcome, many predictors (adjusted associations).</li>
<li><strong>Multivariate</strong>: multiple related outcomes modeled <strong>together</strong> (one overall test per predictor, often more precision).</li>
<li><strong>Fixed effects (repeated measures)</strong>: many observations per patient; estimate <strong>within-patient</strong> effects while removing their constant traits.</li>
<li><strong>Logistic</strong>: multivariable model for a <strong>binary</strong> outcome (report <strong>odds ratios</strong>).</li>
<li><strong>Cox</strong>: multivariable model for <strong>time-to-event</strong> (report <strong>hazard ratios</strong>; check proportional hazards).</li>
</ul>
</section>
</section>
<section id="covariate-selection-with-dags-confounders-colliders-mediators" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Covariate Selection with DAGs (Confounders, Colliders, Mediators)</h1>
<section id="why-this-section" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="why-this-section"><span class="header-section-number">2.1</span> Why this section?</h2>
<p>Multivariable regression answers <strong>conditional</strong> questions (“association of (X) with (Y) holding (Z) constant”). But <strong>what should we hold constant?</strong> Adjusting for the wrong variables can:</p>
<ul>
<li>reduce bias (<strong>good</strong>; e.g., adjusting for confounders),</li>
<li><strong>create</strong> bias (e.g., adjusting for colliders or mediators when estimating a <strong>total</strong> effect),</li>
<li>waste precision (e.g., adjusting for pure noise).</li>
</ul>
<p>Directed acyclic graphs (<strong>DAGs</strong>) give a transparent, pre-analysis way to decide.</p>
<hr>
</section>
<section id="define-the-estimand-first" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="define-the-estimand-first"><span class="header-section-number">2.2</span> Define the estimand first</h2>
<p>Before deciding on a model, determine your target causal quantity:</p>
<ul>
<li><strong>Total effect</strong> of exposure (A) on outcome (Y): effect of changing (A) <strong>allowing</strong> downstream pathways (mediators) to change.</li>
<li><strong>Direct effect</strong> (often controlled/conditional): effect of changing (A) <strong>holding a mediator (M) fixed</strong> at some value.</li>
<li><strong>Associational</strong> (predictive) effect: best prediction of (Y) given (A) and other features, regardless of causality.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Rule:</strong> Adjustments differ by estimand. For <strong>total effects</strong>, <strong>do not adjust for mediators</strong>. For <strong>direct effects</strong>, <strong>do</strong>.</p>
</blockquote>
<hr>
</section>
<section id="cast-of-variables-covariates" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="cast-of-variables-covariates"><span class="header-section-number">2.3</span> Cast of variables (Covariates)</h2>
<ul>
<li><p><strong>Confounder (C):</strong> A common cause of exposure (A) and outcome (Y). Failing to adjust for (C) biases the (AY) effect. <em>Heuristic:</em> occurs <strong>before</strong> (A), affects both (A) and (Y).</p></li>
<li><p><strong>Mediator (M):</strong> Lies <strong>on the pathway</strong> from (A) to (Y). Adjusting for (M) <strong>removes part of the effect</strong> (good only if you want a <strong>direct</strong> effect). <em>Heuristic:</em> occurs <strong>after</strong> (A), affected by (A), affects (Y).</p></li>
<li><p><strong>Collider (K):</strong> A common effect of two variables (e.g., of (A) and some (U) that also affects (Y)). <strong>Adjusting for K opens a spurious path</strong> and <strong>creates bias</strong> (collider bias). <em>Heuristic:</em> if two arrows point <strong>into</strong> K, <strong>don’t condition</strong> on it (or its descendants).</p></li>
<li><p><strong>Instrument (Z_IV):</strong> Affects (A) but affects (Y) <strong>only through (A)</strong> and is independent of the confounders. <strong>Do not adjust</strong> for instruments in simple outcome models; doing so can <strong>increase bias</strong> when unmeasured confounding exists.</p></li>
<li><p><strong>Precision variable (P):</strong> A cause of (Y) <strong>only</strong> (not of (A)), not a mediator/collider. Adjusting for (P) can improve precision and rarely hurts (if no other pitfalls).</p></li>
</ul>
<hr>
</section>
<section id="dag-basics" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="dag-basics"><span class="header-section-number">2.4</span> DAG basics</h2>
<ul>
<li><p>Nodes = variables; arrows = direct causal effects.</p></li>
<li><p>Paths connect (A) and (Y). A path is <strong>open</strong> by default unless blocked by conditioning rules:</p>
<ul>
<li>Conditioning on a <strong>non-collider</strong> blocks paths through it.</li>
<li>Conditioning on a <strong>collider (or its descendant)</strong> <strong>opens</strong> the path.</li>
</ul></li>
</ul>
<p><strong>Back-door criterion (for total effect (A</strong>Y)): Find a set (S) of variables such that:</p>
<ol type="1">
<li>No member of (S) is a <strong>descendant of (A)</strong> (i.e., not a mediator or anything caused by (A)); and</li>
<li><ol start="19" type="A">
<li><strong>blocks every back-door path</strong> from (A) to (Y) (every path that enters (A) through a back arrow).</li>
</ol></li>
</ol>
<hr>
</section>
<section id="step-by-step-how-to-select-covariates" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="step-by-step-how-to-select-covariates"><span class="header-section-number">2.5</span> Step-by-step: How to select covariates?</h2>
<ol type="1">
<li><p><strong>State the estimand.</strong> e.g., “Total effect of maternal smoking ((A)) on infant low birth weight ((Y)).”</p></li>
<li><p><strong>Time order the variables.</strong> Draw what happens <strong>before</strong> exposure, <strong>after</strong> exposure, and at/after outcome.</p></li>
<li><p><strong>Sketch a DAG</strong> with only variables relevant to (A) and (Y). Don’t aim for perfect truth; aim for a defensible working model.</p></li>
<li><p><strong>Identify and list:</strong></p>
<ul>
<li>Pre-exposure common causes of (A) and (Y) (<strong>confounders</strong>) → <strong>adjust</strong>.</li>
<li>Variables caused by (A) (<strong>mediators/descendants</strong>) → <strong>do not adjust</strong> for total effects.</li>
<li>Variables that are effects of (A) and of an unmeasured factor (U) (<strong>colliders/selection nodes</strong>) → <strong>do not adjust</strong>.</li>
<li>Pure instruments (<strong>affect (A) only</strong>) → <strong>do not adjust</strong>.</li>
<li>Outcome-only causes (<strong>precision variables</strong>) → consider adjusting to improve precision.</li>
</ul></li>
<li><p><strong>Document decisions</strong> in your methods (a small DAG figure + list of adjusted covariates and rationale).</p></li>
</ol>
<hr>
</section>
<section id="a-conceptual-example" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="a-conceptual-example"><span class="header-section-number">2.6</span> A conceptual example</h2>
<p><strong>Question:</strong> Total effect of <strong>smoking in pregnancy (A)</strong> on <strong>low birth weight (Y)</strong>.</p>
<ul>
<li>Likely <strong>confounders (C)</strong>: maternal age, socioeconomic status (SES), prior obstetric risk, region.</li>
<li>Likely <strong>mediators (M)</strong>: placental dysfunction, fetal growth restriction, gestational age.</li>
<li>Potential <strong>collider/selection (K)</strong>: attending intensive prenatal care if it is influenced by both smoking and latent risk.</li>
<li>Potential <strong>instrument-ish (Z)</strong>: local cigarette tax (affects smoking; plausibly affects LBW only through smoking).</li>
</ul>
<p><strong>Decision for total effect:</strong> Adjust for <strong>C</strong> (age, SES, obstetric risk, region). <strong>Do not adjust</strong> for (M) (gestational age) or (K) (prenatal care) or for (Z) (tax).</p>
<hr>
</section>
<section id="what-not-to-do-common-pitfalls" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="what-not-to-do-common-pitfalls"><span class="header-section-number">2.7</span> What <strong>not</strong> to do (common pitfalls)?</h2>
<ul>
<li><p><strong>P-value selection (“p &lt; 0.2 in univariable → include”)</strong><br>
Ignores the causal structure; may drop true confounders and keep colliders.<br>
<em>Example:</em> SES is a true confounder of smoking → LBW but has p = 0.23 univariately—dropping it leaves confounding.</p></li>
<li><p><strong>Adjusting for post-exposure variables when estimating a <em>total</em> effect</strong><br>
Overadjustment—removes part of the effect that flows through mediators.<br>
<em>Example:</em> Including gestational age when estimating smoking’s <strong>total</strong> effect on LBW attenuates the effect toward the direct effect.</p></li>
<li><p><strong>Adjusting for colliders / selection variables</strong><br>
Conditioning on a collider opens a spurious path and creates bias.<br>
<em>Example:</em> Adjusting for intensive prenatal care (affected by smoking and latent risk) induces collider bias in smoking → LBW.</p></li>
<li><p><strong>Including instruments (IVs) as outcome-model covariates</strong><br>
With unmeasured confounding, adding an instrument amplifies bias (“Z-bias”).<br>
<em>Example:</em> Controlling for local cigarette tax in the LBW regression can worsen bias if unmeasured risk affects both smoking and LBW.</p></li>
<li><p><strong>Omitting time (wrong temporal ordering)</strong><br>
Misclassifies mediators/confounders and can introduce overadjustment or collider bias.<br>
<em>Example:</em> Treating delivery-time BMI as a baseline confounder (when smoking influences weight gain) wrongly adjusts for a mediator.</p></li>
</ul>
<hr>
</section>
<section id="precision-variables-and-efficiency" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="precision-variables-and-efficiency"><span class="header-section-number">2.8</span> Precision variables and efficiency</h2>
<p>If (P) causes (Y) but not (A) (and is not a mediator/collider), adjusting for (P) can <strong>shrink residual variance</strong> and improve confidence interval width with minimal bias risk.</p>
<blockquote class="blockquote">
<p>Example: (A) = assignment to a low-sodium diet; (Y) = systolic BP at 6 months; (P) = cuff size used and room temperature during measurement. If cuff size/temperature affect BP measurement but are unrelated to diet assignment and not affected by diet, including them reduces residual variance in (Y) and <strong>tightens the CI</strong> for the diet effect.</p>
</blockquote>
<hr>
</section>
<section id="positivity-overlap-and-modelability-checks" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="positivity-overlap-and-modelability-checks"><span class="header-section-number">2.9</span> Positivity (overlap) and modelability checks</h2>
<ul>
<li><p><strong>Positivity:</strong> For every combination of confounders in your data, there should be some exposed and some unexposed units.</p>
<ul>
<li>Check via overlap plots / propensity score histograms.</li>
<li>If violated, consider coarsening covariates, trimming non-overlap, or changing the estimand (e.g., to the <strong>overlap population</strong>).</li>
</ul></li>
<li><p><strong>Missingness:</strong> Prefer pre-specified handling (multiple imputation) done <strong>before</strong> causal estimation, preserving the DAG’s temporal order.</p></li>
<li><p><strong>Sample size vs.&nbsp;parameters:</strong> For logistic/Cox models, aim for adequate information (e.g., events-per-parameter () as a <strong>rough</strong> guide) or consider penalization.</p></li>
</ul>
<hr>
</section>
<section id="time-varying-confounding" class="level2" data-number="2.10">
<h2 data-number="2.10" class="anchored" data-anchor-id="time-varying-confounding"><span class="header-section-number">2.10</span> Time-varying confounding</h2>
<p>When confounders are themselves affected by prior exposure (e.g., smoking () weight change () disease; and weight also affects future smoking), standard regression adjustment can be biased. Use <strong>marginal structural models (MSMs)</strong> with <strong>inverse probability weighting</strong> or <strong>g-methods</strong>. The DAG still clarifies the structure; the estimation method changes.</p>
<hr>
</section>
<section id="summary-1" class="level2" data-number="2.11">
<h2 data-number="2.11" class="anchored" data-anchor-id="summary-1"><span class="header-section-number">2.11</span> Summary</h2>
<ul>
<li><strong>Estimand:</strong> “Total effect of (A) on (Y).”</li>
<li><strong>DAG rationale:</strong> “We constructed a pre-specified DAG based on prior literature and domain expertise.”</li>
<li><strong>Adjustment set:</strong> “We adjusted for ({C_1, C_2, }) to block all back-door paths per the DAG; no descendants of (A) were included.”</li>
<li><strong>Excluded variables and reasons:</strong> “We did not adjust for mediator(s) ({M}), collider(s)/selection node(s) ({K}), or instrument(s) ({Z}).”</li>
<li><strong>Software:</strong> “DAG evaluation with <code>dagitty::adjustmentSets</code>; models fit in R.”</li>
</ul>
<hr>
<p><em>End of section.</em></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>