<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Muji Chughtai">
<meta name="dcterms.date" content="2026-06-17">
<meta name="keywords" content="<p>OLS, Regression, Continuous Varibales, Categorical Variables, R, Julia, <code>glm</code>, <code>lm</code>, <code>t.test</code>, <code>anova</code></p>">

<title>Ordinary Least Square Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="olsregression_files/libs/clipboard/clipboard.min.js"></script>
<script src="olsregression_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="olsregression_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="olsregression_files/libs/quarto-html/popper.min.js"></script>
<script src="olsregression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="olsregression_files/libs/quarto-html/anchor.min.js"></script>
<link href="olsregression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="olsregression_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="olsregression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="olsregression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="olsregression_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#performance-in-school" id="toc-performance-in-school" class="nav-link" data-scroll-target="#performance-in-school">Performance in School</a>
  <ul class="collapse">
  <li><a href="#prediction---initial-intuitions" id="toc-prediction---initial-intuitions" class="nav-link" data-scroll-target="#prediction---initial-intuitions">Prediction - Initial Intuitions</a></li>
  <li><a href="#the-equal-means-model" id="toc-the-equal-means-model" class="nav-link" data-scroll-target="#the-equal-means-model">The Equal Means Model</a></li>
  <li><a href="#considering-other-variables" id="toc-considering-other-variables" class="nav-link" data-scroll-target="#considering-other-variables">Considering other Variables</a></li>
  </ul></li>
  <li><a href="#fitting-the-line-of-best-fit" id="toc-fitting-the-line-of-best-fit" class="nav-link" data-scroll-target="#fitting-the-line-of-best-fit">Fitting the Line of Best Fit</a>
  <ul class="collapse">
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions">Assumptions</a>
  <ul class="collapse">
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">1. Linearity</a></li>
  <li><a href="#homoscedasticity-of-errors" id="toc-homoscedasticity-of-errors" class="nav-link" data-scroll-target="#homoscedasticity-of-errors">2. Homoscedasticity of errors</a></li>
  <li><a href="#no-autocorrelation-of-errors" id="toc-no-autocorrelation-of-errors" class="nav-link" data-scroll-target="#no-autocorrelation-of-errors">3. No autocorrelation of errors</a></li>
  <li><a href="#linear-independence-of-the-predictor-variables" id="toc-linear-independence-of-the-predictor-variables" class="nav-link" data-scroll-target="#linear-independence-of-the-predictor-variables">4. Linear independence of the predictor variables</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#implementation---performance-in-school" id="toc-implementation---performance-in-school" class="nav-link" data-scroll-target="#implementation---performance-in-school">Implementation - Performance in School</a>
  <ul class="collapse">
  <li><a href="#fitting-the-model-using-lm" id="toc-fitting-the-model-using-lm" class="nav-link" data-scroll-target="#fitting-the-model-using-lm">Fitting the Model using <code>lm</code></a></li>
  <li><a href="#assessing-linearity" id="toc-assessing-linearity" class="nav-link" data-scroll-target="#assessing-linearity">Assessing Linearity</a></li>
  <li><a href="#assessing-homoscedasticity-of-errors" id="toc-assessing-homoscedasticity-of-errors" class="nav-link" data-scroll-target="#assessing-homoscedasticity-of-errors">Assessing Homoscedasticity of Errors</a></li>
  <li><a href="#assessing-no-autocorrelation-of-errors" id="toc-assessing-no-autocorrelation-of-errors" class="nav-link" data-scroll-target="#assessing-no-autocorrelation-of-errors">Assessing No Autocorrelation of Errors</a></li>
  <li><a href="#assessing-linear-independence-of-the-predictor-variables" id="toc-assessing-linear-independence-of-the-predictor-variables" class="nav-link" data-scroll-target="#assessing-linear-independence-of-the-predictor-variables">Assessing Linear Independence of the Predictor Variables</a></li>
  <li><a href="#interim-conclusion---simple-linear-regression" id="toc-interim-conclusion---simple-linear-regression" class="nav-link" data-scroll-target="#interim-conclusion---simple-linear-regression">Interim Conclusion - Simple Linear Regression</a></li>
  </ul></li>
  <li><a href="#considering-categorical-variables" id="toc-considering-categorical-variables" class="nav-link" data-scroll-target="#considering-categorical-variables">Considering Categorical Variables</a>
  <ul class="collapse">
  <li><a href="#math-scores-by-different-types-of-primary-schools" id="toc-math-scores-by-different-types-of-primary-schools" class="nav-link" data-scroll-target="#math-scores-by-different-types-of-primary-schools">Math Scores by Different Types of Primary Schools</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Ordinary Least Square Regression</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><a href="https://github.com/mujtabachughtai">Muji Chughtai</a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Psychology, Yale University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>This research guide provides an introdcution to ordinary least square regression (OLS), including the theoretical and mathematical background of OLS, the assumptions of OLS, when to use OLS in practice, how to implement OLS regression, and how to interpret results from OLS regression.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p></p><p>OLS, Regression, Continuous Varibales, Categorical Variables, R, Julia, <code>glm</code>, <code>lm</code>, <code>t.test</code>, <code>anova</code></p><p></p>
  </div>
</div>

</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Regression <span class="citation" data-cites="montgomery2021introduction">(<a href="#ref-montgomery2021introduction" role="doc-biblioref">Montgomery, Peck, and Vining 2021</a>)</span> is a powerful body of statistical methods for constructing equations to describe the relationship between a <em>response</em> variable (often referred to as a dependent or outcome variable) and a set of <em>predictor</em> variables (often referred to as independent variables). Regression models can be used for all three of the primary goals of statistical analysis:</p>
<ol type="1">
<li><strong>Description</strong>: to describe the relationship between response and predictor variables</li>
<li><strong>Inference</strong>: to infer relationships in a population based on relationships in a sample from that population</li>
<li><strong>Prediction</strong>: to predict future values of a response variable based on values of the predictor variables</li>
</ol>
<p>Ordinary least squares (OLS) regression is the most common method for estimating a linear regression model. In this guide, we’ll discuss when to use OLS, the assumptions of OLS, how to implement OLS regression, and how to interpret results from OLS regression. Let’s start with a guiding example.</p>
</section>
<section id="performance-in-school" class="level1">
<h1>Performance in School</h1>
<p>Educators, students, and parents are often quite invested in students’ performance on standardized tests. These test scores often play a large role in a student’s ability to be accepted into selective high schools and colleges.</p>
<p><strong>The California Test Score Dataset</strong> contains data on test performance, school characteristics, and student demographic backgrounds for primary schools in California <span class="citation" data-cites="AER">(<a href="#ref-AER" role="doc-biblioref">Kleiber and Zeileis 2026</a>)</span>. Using this dataset, we will assess how linear models (and specifically, ordinary least squares regression) can help us describe, infer from, and make predictions about test performance among these students.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dataset we will be using</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"CASchools"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># package for cleaning and organizing data</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="prediction---initial-intuitions" class="level2">
<h2 class="anchored" data-anchor-id="prediction---initial-intuitions">Prediction - Initial Intuitions</h2>
</section>
<section id="the-equal-means-model" class="level2">
<h2 class="anchored" data-anchor-id="the-equal-means-model">The Equal Means Model</h2>
<p>Imagine that you work for the California’s State Department of Education. You have been sent to visit a randomly selected school in the state. What would you expect the average test score to be in this school? An initial guess might be <strong>the average test score across all school districts in the state</strong>. Let’s take a look at what this average is, and how all school districts relate to this average.</p>
<p>Here are the variables in the dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the first few rows of the dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(CASchools),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"California Test Score Dataset for First 5 Schools "</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>California Test Score Dataset for First 5 Schools</caption>
<colgroup>
<col style="width: 6%">
<col style="width: 22%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">district</th>
<th style="text-align: left;">school</th>
<th style="text-align: left;">county</th>
<th style="text-align: left;">grades</th>
<th style="text-align: right;">students</th>
<th style="text-align: right;">teachers</th>
<th style="text-align: right;">calworks</th>
<th style="text-align: right;">lunch</th>
<th style="text-align: right;">computer</th>
<th style="text-align: right;">expenditure</th>
<th style="text-align: right;">income</th>
<th style="text-align: right;">english</th>
<th style="text-align: right;">read</th>
<th style="text-align: right;">math</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">75119</td>
<td style="text-align: left;">Sunol Glen Unified</td>
<td style="text-align: left;">Alameda</td>
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">195</td>
<td style="text-align: right;">10.90</td>
<td style="text-align: right;">0.5102</td>
<td style="text-align: right;">2.0408</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">6384.911</td>
<td style="text-align: right;">22.690001</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">691.6</td>
<td style="text-align: right;">690.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">61499</td>
<td style="text-align: left;">Manzanita Elementary</td>
<td style="text-align: left;">Butte</td>
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">240</td>
<td style="text-align: right;">11.15</td>
<td style="text-align: right;">15.4167</td>
<td style="text-align: right;">47.9167</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">5099.381</td>
<td style="text-align: right;">9.824000</td>
<td style="text-align: right;">4.583334</td>
<td style="text-align: right;">660.5</td>
<td style="text-align: right;">661.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">61549</td>
<td style="text-align: left;">Thermalito Union Elementary</td>
<td style="text-align: left;">Butte</td>
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">1550</td>
<td style="text-align: right;">82.90</td>
<td style="text-align: right;">55.0323</td>
<td style="text-align: right;">76.3226</td>
<td style="text-align: right;">169</td>
<td style="text-align: right;">5501.955</td>
<td style="text-align: right;">8.978000</td>
<td style="text-align: right;">30.000002</td>
<td style="text-align: right;">636.3</td>
<td style="text-align: right;">650.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">61457</td>
<td style="text-align: left;">Golden Feather Union Elementary</td>
<td style="text-align: left;">Butte</td>
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">243</td>
<td style="text-align: right;">14.00</td>
<td style="text-align: right;">36.4754</td>
<td style="text-align: right;">77.0492</td>
<td style="text-align: right;">85</td>
<td style="text-align: right;">7101.831</td>
<td style="text-align: right;">8.978000</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">651.9</td>
<td style="text-align: right;">643.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">61523</td>
<td style="text-align: left;">Palermo Union Elementary</td>
<td style="text-align: left;">Butte</td>
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">1335</td>
<td style="text-align: right;">71.50</td>
<td style="text-align: right;">33.1086</td>
<td style="text-align: right;">78.4270</td>
<td style="text-align: right;">171</td>
<td style="text-align: right;">5235.988</td>
<td style="text-align: right;">9.080333</td>
<td style="text-align: right;">13.857677</td>
<td style="text-align: right;">641.8</td>
<td style="text-align: right;">639.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">62042</td>
<td style="text-align: left;">Burrel Union Elementary</td>
<td style="text-align: left;">Fresno</td>
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">137</td>
<td style="text-align: right;">6.40</td>
<td style="text-align: right;">12.3188</td>
<td style="text-align: right;">86.9565</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">5580.147</td>
<td style="text-align: right;">10.415000</td>
<td style="text-align: right;">12.408759</td>
<td style="text-align: right;">605.7</td>
<td style="text-align: right;">605.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let’s first investigate the test score for <code>math</code>. The average test score for <code>math</code> across all schools is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># average math test score across all schools</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(CASchools<span class="sc">$</span>math)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 653.3426</code></pre>
</div>
</div>
<p>So, a relatively reasonable guess for the test score of the random school we are visiting is 653.34. But how good of a guess is this? Let’s look at the distribution of test scores across all schools, and see where this mean value falls relative to the rest of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot of distribution of math test scores across all schools with mean value marked</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> math)) <span class="sc">+</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math), <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Math Test Scores Across All Schools"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Math Test Score"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As is common with much real-life data, the mean of the <code>math</code> variable seems to be at the center of the distribution, and many observations seem to be relatively near the mean. However, many observations are also quite <strong>far</strong> from the mean, and <strong>only about 3% of observations are within one point of the mean:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># percentage of observations within one point of the mean</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">abs</span>(CASchools<span class="sc">$</span>math <span class="sc">-</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math)) <span class="sc">&lt;</span> <span class="dv">1</span>) <span class="sc">/</span> <span class="fu">nrow</span>(CASchools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03333333</code></pre>
</div>
</div>
<p>As such, although the mean math score across all schools may be <em>close</em> to the math score of a randomly selected school, this guess can drastically be improved. How so?</p>
<p>Well, we can leverage the fact that we also have access <strong>to other data for each school,</strong> and this other data may <strong>be highly predictive of that school’s math score.</strong></p>
</section>
<section id="considering-other-variables" class="level2">
<h2 class="anchored" data-anchor-id="considering-other-variables">Considering other Variables</h2>
<p>Let’s plot the relationship between a school’s math score and a variable that we might believe is related: that school’s reading score. An initial hypothesis could be that schools with <strong>higher reading scores might have higher math scores</strong> (i.e, a hypothesis resting on the assumption that some schools are better or worse at both types of test). Another competing hypothesis could be that schools with <strong>higher reading scores might have lower math scores</strong> (i.e., a hypothesis resting on the assumption that some schools might be better at math, but this may be at the cost of a reading).</p>
<p>To get an initial sense on if either of these hypotheses are reasonable, we can plot a scatterplot of the <code>math</code> and <code>read</code> variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot of math vs read test scores</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> read, <span class="at">y =</span> math)) <span class="sc">+</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Math vs Reading Test Scores"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading Test Score"</span>, <span class="at">y =</span> <span class="st">"Math Test Score"</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on this plot, it certainly looks like schools with higher reading scores also tend to have higher math scores. As such, when we reconsider the equal-means model from earlier, we can get already begin to easily think of ways to improve that model. Specifically, since we know that schools higher in one score tend to be higher in another, if we know a school is above the average in reading, we can predict that it is also likely to be above the average in math. Similarly, if we know a school is below the average in reading, we can predict that it is also likely to be below the average in math:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot of math vs read test scores with average math score</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and average reading  score marked</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> read, <span class="at">y =</span> math)) <span class="sc">+</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>read), <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math), <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span> </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Scatterplot of Math vs Reading Test Scores with Averages Marked"</span>,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading Test Score"</span>, <span class="at">y =</span> <span class="st">"Math Test Score"</span>) <span class="sc">+</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>By looking at the plot above, we can see that most points fall in the lower-left corner and the upper right corner. That is, schools tend tend to be either above average in both reading and math, or below average in both reading and math. This suggests that <strong>we can make a better prediction about a school’s math score (and it’s relationship to the mean) if we also know that school’s reading score.</strong> Specifically, if we know a school is above average in reading, we can predict that it is also likely to be above average in math. Similarly, if we know a school is below average in reading, we can predict that it is also likely to be below average in math.</p>
<p>However, this is still a very simple model. What if we want to know the magnitude of how far a school’s math score is from the mean, based on how far that school’s reading score is from the mean? Better yet, <strong>what if we didn’t even have to directly consider the mean, and with just a school’s reading score, we could predict that school’s math score?</strong></p>
<p>With OLS regression for one predictor variable, we can find the line of the form <span class="math inline">\(Y = \beta_0 + X\beta_1\)</span> , where <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are our <strong>regression coefficients</strong> that best fit the data. We can use this equation to make highly precise predictions about a school’s math score based on that school’s reading score.</p>
</section>
</section>
<section id="fitting-the-line-of-best-fit" class="level1">
<h1>Fitting the Line of Best Fit</h1>
<p>There are an infinite number of lines that can be “fit” to a scatterplot of two variables.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 1 - A Scatterplot with Many Lines</figcaption>
<p><img src="plot_manylines.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>How do we know what line best fits the data? Different methods differ in how they choose the “best” line for the data.</p>
<p>In OLS regression, this is done by <strong>minimizing the sum of squared residuals (SSR)</strong>. A <strong>residual</strong> is the difference between the observed dependent variable, <span class="math inline">\(Y\)</span>, and the fitted or predicted values of the dependent variable, <span class="math inline">\(\hat{Y}\)</span>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 2 - A Fitted Line with Residuals</figcaption>
<p><img src="plot_bestline.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>For OLS regression with one predictor, we obtain fitted values using the regression equation <span class="math inline">\(\hat{Y} = \hat{\beta}_0 + X\hat{\beta}_1\)</span>, where <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> are the estimated regression coefficients. So, in this setting, we want to find the values of <span class="math inline">\(\beta\)</span> that minimize:</p>
<p><span class="math display">\[
\sum_{i=1}^n y_i - \beta_0 - X_i\beta_1
\]</span><br>
</p>
<p>For OLS regression with multiple predictors, we obtain fitted values using the regression equation <span class="math inline">\(\hat{Y} = \hat{\beta}_0 + X_1\hat{\beta}_1 + X_2\hat{\beta}_2 + ... + X_k\hat{\beta}_k\)</span>, where <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> are the estimated regression coefficients. So, in this setting, we want to find the values of <span class="math inline">\(\beta\)</span> that minimize:</p>
<p><span class="math display">\[
\sum_{i=1}^n y_i - \beta_0 - X_{1i}\beta_1 - X_{2i}\beta_2 - ... - X_{ki}\beta_k
\]</span></p>
<p>While most researchers use statistical software to estimate regression coefficients, we can also calculate the coefficients manually (so long as we are comfortable with some linear algebra). First we define <strong>X</strong> as the design matrix (in the case of one independent variable, the design matrix has two columns – the first is a column of 1s to represent the intercept, and the second is our X values). As such, predicted coefficients can be calculated using the following formula:</p>
<p><span class="math display">\[
\hat{\beta} = (\textbf{X}^T\textbf{X})^{-1}\textbf{X}^T\text{y}
\]</span></p>
<section id="assumptions" class="level2">
<h2 class="anchored" data-anchor-id="assumptions">Assumptions</h2>
<p>For a model to give valid and meaningful results, certain assumptions are necessary. If any of these are violated, the results may not be valid.</p>
<section id="linearity" class="level3">
<h3 class="anchored" data-anchor-id="linearity">1. Linearity</h3>
<p>Linearity is the assumption that the relationship between the dependent and independent variable is linear.</p>
<section id="assessing-and-addressing-violations" class="level4">
<h4 class="anchored" data-anchor-id="assessing-and-addressing-violations">Assessing and Addressing Violations</h4>
<p>We can assess the linearity assumption by creating a scatter plot of the predictor and outcome variables. If there seems to be a a nonlinear relationship, the assumption is violated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 3 - A relationship where the linearity assumption holds</figcaption>
<p><img src="plot_linearity.png" class="img-fluid figure-img"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 4 - A relationship where the linearity assumption does not hold</figcaption>
<p><img src="plots_curve.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>The two main ways to address a violation of linearity are:</p>
<ol type="1">
<li><p><strong>Transform the data</strong> - Applying a function to the variables, like a log function (e.g., <span class="math inline">\(\log(y)\)</span>) or an exponential function (e.g., <span class="math inline">\(e^y\)</span>), can often transform the data to make the relationship linear. However, interpretations of the now linear relationship should be cautious to use transformed scales.</p></li>
<li><p><strong>Fit a nonlinear model</strong> - An alternative regression model, like a GLM, might be better suited to fit a non-linear relationship than OLS regression.</p></li>
</ol>
</section>
</section>
<section id="homoscedasticity-of-errors" class="level3">
<h3 class="anchored" data-anchor-id="homoscedasticity-of-errors">2. Homoscedasticity of errors</h3>
<p>Homoscedasticity of errors is the assumption that the error terms have equal variance across values of the predictor variable. As such, this assumption could be violated when the variance of the outcome variable changes across values of a predictor variable. For example, if we look to model someone’s <strong>income</strong> vs their <strong>expenditures</strong>, we might expect to find greater variability in how much money individuals with higher incomes spend vs individuals with lower incomes (i.e., variability in the outcome variable would increase with larger predictor variables). As such, the homescedasticity of errors assumption would likely be violated for this relationship.</p>
<section id="assessing-and-addressing-violations-1" class="level4">
<h4 class="anchored" data-anchor-id="assessing-and-addressing-violations-1">Assessing and Addressing Violations</h4>
<p>We can check this assumption by plotting the model residuals vs the predicted values. The points should look randomly scattered. If we see a pattern in the distribution of the residuals, the assumption is violated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 5 - A residual plot indicating that homoscedasticitiy holds</figcaption>
<p><img src="plot_resid1.png" class="img-fluid figure-img"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 6 - A residual plot indicating that homoscedasticitiy does not hold</figcaption>
<p><img src="plot_resid2.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>We can also check for homoscedasticity using a test such as the Breush-Pagan test <span class="citation" data-cites="lmtest_bptest">(<a href="#ref-lmtest_bptest" role="doc-biblioref">Hothorn et al. 2024a</a>)</span> or the White test <span class="citation" data-cites="whitestrap_white_test">(<a href="#ref-whitestrap_white_test" role="doc-biblioref"><em>White’s Test</em> 2019</a>)</span>.</p>
<p>The two main ways to address a violation of homoscedastic errors are:</p>
<ol type="1">
<li><p><strong>Transform the data</strong> - Applying a transformation, like a log function (e.g., <span class="math inline">\(\log(y)\)</span>) or a square root function (e.g., <span class="math inline">\(\sqrt y\)</span>), can often make heteroscedastic errors more constant.</p></li>
<li><p><strong>Fit a weighted least squares regression model</strong> - Weighted least squares regression can better account for heteroscedasticity by minimizing a weighted sum of squared residuals.</p></li>
<li><p><strong>Use robust standard errors</strong> - Using robust (e.g., Huber-White) standard errors provides reliable estimates of the coefficient standard errors, even when the errors are heteroscedastic <span class="citation" data-cites="zeileis2020sandwich">(<a href="#ref-zeileis2020sandwich" role="doc-biblioref">Zeileis, Köll, and Graham 2020</a>)</span>.</p></li>
</ol>
</section>
</section>
<section id="no-autocorrelation-of-errors" class="level3">
<h3 class="anchored" data-anchor-id="no-autocorrelation-of-errors">3. No autocorrelation of errors</h3>
<p>No autocorrelations of errors is the assumption that errors of different observations are not correlated. This assumption is often violated in the case of time series data, where observations close in time may be highly correlated.</p>
<section id="assessing-and-addressing-violations-2" class="level4">
<h4 class="anchored" data-anchor-id="assessing-and-addressing-violations-2">Assessing and Addressing Violations</h4>
<p>We can check this assumption by plotting the residuals against any possible ordering variable (e.g., time). The points should look randomly scattered. If we see a pattern in the distribution of the residuals, the assumption is likely violated.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 6 - A residual plot across time indicating no autocorrelation</figcaption>
<p><img src="plot_noac.png" class="img-fluid figure-img"></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<figcaption>Figure 7 - A residual plot across time indicating autocorrelation</figcaption>
<p><img src="plot_ac.png" class="img-fluid figure-img"></p>
</figure>
</div>
<p>We can also check for autocorrelation using a test such as the Durban-Watson test <span class="citation" data-cites="lmtest_dwtest">(<a href="#ref-lmtest_dwtest" role="doc-biblioref">Hothorn et al. 2024b</a>)</span> or the Breusch-Godfrey test.</p>
<p>The main way to address a violation of no autocorrelation is to use an autoregressive model instead <span class="citation" data-cites="burant2022autoregressive">(<a href="#ref-burant2022autoregressive" role="doc-biblioref">Burant 2022</a>)</span>.</p>
</section>
</section>
<section id="linear-independence-of-the-predictor-variables" class="level3">
<h3 class="anchored" data-anchor-id="linear-independence-of-the-predictor-variables">4. Linear independence of the predictor variables</h3>
<p>This assumption applies when there is more than one predictor variable (i.e., when fitting a multiple linear regression model). Linear independence of the predictor variables variables is the assumption that no predictor variable can be expressed as an exact linear combination of the others. This ensures that the variables contain unique information, and that the regression coefficients can be estimated without ambiguity. When this assumption is violated, it is referred to as <strong>multicollinearity</strong>.</p>
<section id="assessing-and-addressing-violations-3" class="level4">
<h4 class="anchored" data-anchor-id="assessing-and-addressing-violations-3">Assessing and Addressing Violations</h4>
<p>We can check this assumption by calculating a correlation matrix of all pairwise correlations between predictor variables. A value of 1 or -1 indicates perfect multicollinearity, while a value close to 1 indicates high multicollinearity.</p>
<p>We can also calculate the <strong>Variance Inflation Factor</strong> to determine how much the variance of a regression coefficient is increased due to multicollinearity <span class="citation" data-cites="thompson2017vif">(<a href="#ref-thompson2017vif" role="doc-biblioref">Thompson et al. 2017</a>)</span>. A high VIF, such as VIF <span class="math inline">\(&gt;5\)</span>, indicates high multicollinearity.</p>
<p>To simplest way to address multicollinearity is to remove one of the collinear variables from the model.</p>
</section>
</section>
</section>
</section>
<section id="implementation---performance-in-school" class="level1">
<h1>Implementation - Performance in School</h1>
<p>Now we that we know what assumptions to test when fitting an OLS regression model, let’s use OLS regression with our school performance data from earlier. Specifically, let’s fit a model that predicts a school’s math score based on that school’s reading score. Since our predictor variable is a school’s reading score and our outcome variable is a school’s math score, we can write our model as a linear equation:</p>
<p><span class="math display">\[
\text{Math Score} = \beta_0 + \text{Reading Score}\times\beta_1
\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> is the intercept (i.e., the expected math score when reading score is 0) and <span class="math inline">\(\beta_1\)</span> is the slope (i.e., the expected change in math score for a one unit increase in reading score). Note that in this case, the intercept is not meaningful since a reading score of 0 is not possible (in other examples, the intercept may be meaningful, such as when modeling someone’s income based on their years of higher education, where the intercept would represent the expected income for someone with 0 years of higher education). In our case, the slope is the more meaningful coefficient, as it represents the expected change in math score for a one unit increase in reading score.</p>
<p>Let’s fit this model using the <code>lm</code> function in R, interpret the results, and assess the assumptions to confrim that our interpretations are valid.</p>
<section id="fitting-the-model-using-lm" class="level2">
<h2 class="anchored" data-anchor-id="fitting-the-model-using-lm">Fitting the Model using <code>lm</code></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_math_read <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> read, <span class="at">data =</span> CASchools)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_math_read)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math ~ read, data = CASchools)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.4897  -4.2335   0.5528   4.2775  23.1307 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 89.56580   11.50984   7.782 5.67e-14 ***
read         0.86077    0.01756  49.005  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.23 on 418 degrees of freedom
Multiple R-squared:  0.8517,    Adjusted R-squared:  0.8514 
F-statistic:  2402 on 1 and 418 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From the output above, we can see that the estimated intercept is about 89.566, and the estimated slope is about 0.861. <strong>This means that for every one unit increase in reading score, we expect a 0.861 point increase in math score.</strong> Note that this equation allows us to <strong>describe</strong> the relationship between reading and math scores across schools, and to <strong>predict</strong> a school’s math score based on that school’s reading score (relating to the first and third goals of statistical analysis).</p>
<p>Linear model outputs from R also provide t-values and p-values for each coefficient. Generally, the t-value and p-value for the intercept are not of interest, since the intercept is often not meaningful. However, the t-value and p-value for the slope are of interest, since the slope is often the more meaningful coefficient.</p>
<p>The t-value is the estimated coefficient divided by its standard error, and <strong>the p-value is the probability of observing a t-value as extreme as the one observed, under the null hypothesis that the true coefficient is 0</strong>. This relates to the second goal of statistical analysis that regression can help with: <strong>inference</strong>. Specifically, we can use the t-value and p-value to test the <strong>null hypothesis that the true slope at the population-level is 0 (i.e., that there is no relationship between reading score and math score at the population-level)</strong>. Note that the linear model associated with the null hypothesis is equivalent to the equal means model we considered earlier where the predicted math score is just the average math score across all schools and the slope is 0:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatterplot of math vs read test scores with equal means model</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and fitted regression line</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> read, <span class="at">y =</span> math)) <span class="sc">+</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(model_math_read)[<span class="dv">1</span>],</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">coef</span>(model_math_read)[<span class="dv">2</span>], <span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>         <span class="st">"Scatterplot of Math vs Reading Test Scores with Equal Means Model</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="st">and Fitted Regression Line"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading Test Score"</span>, <span class="at">y =</span> <span class="st">"Math Test Score"</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Additionally, by design, the fitted regression line always goes through the point of the mean of the predictor variable and the mean of the outcome variable: <span class="math inline">\((\bar{X}, \bar{Y})\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatterplot of math vs read test scores with mean values marked,</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># fitted regression line, and point of mean intersection marked</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> read, <span class="at">y =</span> math)) <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>read), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math), <span class="at">color=</span><span class="st">"red"</span>, <span class="at">linetype =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(model_math_read)[<span class="dv">1</span>],</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">coef</span>(model_math_read)[<span class="dv">2</span>], <span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"point"</span>, <span class="at">x =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>read), <span class="at">y =</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math),</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"purple"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Math vs Reading Test Scores with</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="st">Fitted Regression Line, Means Marked, and Point of Intersection Marked"</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading Test Score"</span>, <span class="at">y =</span> <span class="st">"Math Test Score"</span>) <span class="sc">+</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>That the t-value for the slope is large and that the p-value is very small (p &lt; .001) suggests that, <strong>at the population level, there is a significant relationship between reading score and math score</strong>. Additionally, since the estimated slope (and associated t-value), is positive, we can infer that the relationship between reading and math scores is also positive at the population-level. However, we should be cautious with what we consider the population in this case. Since all of the schools in this sample were primary schools in California, we can only be confident in our inference about the relationship between reading and math scores for primary schools in California. For example, we cannot be confident in our inference about the relationship between reading and math scores for high schools in California, or for primary schools across the United States.</p>
<p>Regardless, from the model above we can summarise our results with respect to the three goals of statistical analysis as follows:</p>
<ol type="1">
<li><p><strong>Description</strong>: There is a positive relationship between reading and math scores across primary schools in California, such that for every one unit increase in reading score, there is an expected 0.861 point increase in math score.</p></li>
<li><p><strong>Inference</strong>: This relationship does not seem to be due to random chance, and is likely to hold in the population of primary schools in California.</p></li>
<li><p><strong>Prediction</strong>: We can predict a school’s math score based on that school’s reading score using the equation <span class="math inline">\(\hat{Y} = 89.566 + 0.861X\)</span>.</p></li>
</ol>
<p>These are powerful statistical interpretations that we can make from a simple linear regression model! However, we should be cautious in our interpretations if the assumptions of OLS regression are violated. Let’s check these assumptions to confirm that our interpretations are valid.</p>
</section>
<section id="assessing-linearity" class="level2">
<h2 class="anchored" data-anchor-id="assessing-linearity">Assessing Linearity</h2>
<p>From the scatterplots of math and reading scores above, the relationship between these two variables seems to be linear. As such, the linearity assumption seems to hold.</p>
</section>
<section id="assessing-homoscedasticity-of-errors" class="level2">
<h2 class="anchored" data-anchor-id="assessing-homoscedasticity-of-errors">Assessing Homoscedasticity of Errors</h2>
<p>To check the homoscedasticity of errors assumption, we can plot the residuals vs the fitted values from our model. The points should look randomly scattered. If we see a pattern in the distribution of the residuals, this assumption is likely violated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot of residuals vs fitted values</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fitted</span>(model_math_read), <span class="at">y =</span> <span class="fu">resid</span>(model_math_read))) <span class="sc">+</span> </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs Fitted Values for OLS Regression Model of</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="st">Math vs Reading Scores"</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fitted Values"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot above, there does not seem to be a clear pattern in the distribution of the residuals, suggesting that the homoscedasticity of errors assumption holds.</p>
</section>
<section id="assessing-no-autocorrelation-of-errors" class="level2">
<h2 class="anchored" data-anchor-id="assessing-no-autocorrelation-of-errors">Assessing No Autocorrelation of Errors</h2>
<p>To check the no autocorrelation of errors assumption, we can plot the residuals vs an ordering variable. The points should look randomly scattered. If we see a pattern in the distribution of the residuals, this assumption is likely violated:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot of residuals vs fitted values ordered by row</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(CASchools), <span class="at">y =</span> <span class="fu">resid</span>(model_math_read))) <span class="sc">+</span> </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residuals vs Row Number for OLS Regression Model of</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="st">Math vs Reading Scores"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Row Number"</span>, <span class="at">y =</span> <span class="st">"Residuals"</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot above, there does not seem to be a clear pattern in the distribution of the residuals across row number, suggesting that the no autocorrelation of errors assumption holds.</p>
</section>
<section id="assessing-linear-independence-of-the-predictor-variables" class="level2">
<h2 class="anchored" data-anchor-id="assessing-linear-independence-of-the-predictor-variables">Assessing Linear Independence of the Predictor Variables</h2>
<p>Since we only have one predictor variable in this model, the linear independence of the predictor variables assumption is not relevant here. However, if we had more than one predictor variable, we would need to check this assumption by calculating a correlation matrix of all pairwise correlations between predictor variables, and by calculating the Variance Inflation Factor for each predictor variable.</p>
</section>
<section id="interim-conclusion---simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="interim-conclusion---simple-linear-regression">Interim Conclusion - Simple Linear Regression</h2>
<p>Since the assumptions of OLS regression seem to hold, we can be confident in our interpretations of the model coefficients and associated t-values and p-values. Specifically, we can be confident that there is a significant positive relationship between reading and math scores across primary schools in California, such that for every one unit increase in reading score, there is an expected 0.86 point increase in math score.</p>
<p>With respect to our initial question about predicting the math score of a randomly selected school, we can now make a much more precise prediction. Specifically, if we know the reading score of the school, we can use the equation <span class="math inline">\(\hat{Y} = 89.57 + 0.86X\)</span> to predict that school’s math score. For example, if we know a school has a reading score of 700, we can predict that school’s math score as follows:</p>
<p><span class="math display">\[
\hat{Y} = 89.566 + 0.861 \times 700 = 692.266
\]</span></p>
<p>Of course, this point lies on the fitted regression line, and we can see how this point relates to the rest of the data by plotting it on our scatterplot:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatterplot of math vs read test scores with fitted regression line</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and predicted point marked</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> read, <span class="at">y =</span> math)) <span class="sc">+</span> </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(model_math_read)[<span class="dv">1</span>],</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">coef</span>(model_math_read)[<span class="dv">2</span>], <span class="at">color=</span><span class="st">"blue"</span>) <span class="sc">+</span> </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"point"</span>, <span class="at">x =</span> <span class="dv">700</span>, <span class="at">y =</span> <span class="fl">692.266</span>, <span class="at">color =</span> <span class="st">"purple"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of Math vs Reading Test Scores with</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="st">Fitted Regression Line and Predicted Point Marked"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading Test Score"</span>, <span class="at">y =</span> <span class="st">"Math Test Score"</span>) <span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can also see how to fit this linear model using other common statistical software like <code>Python</code> and <code>Stata</code>:</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Python</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Stata</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># # loading necessary libraries</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># import numpy as np</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># import statsmodels.api as sm</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># # loading the dataset from earlier</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="co"># CASchools_py = r.CASchools</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># y = CASchools_py["math"]</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># X = CASchools_py["read"]</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co"># # add intercept, like R's lm() does automatically, to the predictor variable</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="co"># X = sm.add_constant(X)</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># # fit the OLS regression model like before</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># model_math_read_py = sm.OLS(y, X).fit()</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print(model_math_read_py.summary())</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">

</div>
</div>
</div>
</section>
</section>
<section id="considering-categorical-variables" class="level1">
<h1>Considering Categorical Variables</h1>
<p>So far, we have only considered how to use OLS regression to model the relationship between a continuous predictor variable (i.e., reading score) and a continuous outcome variable (i.e., math score). However, OLS regression can also be used to model the relationship between a categorical predictor variable and a continuous outcome variable. There are important and interesting parallels between OLS regression with categorical predictor variables and other linear models such as the <code>t-test</code> (when there are only 2 levels to the predictor variable) and ANOVA (when there are more than 2 levels to the predictor variable).</p>
<p>In our California schools dataset, we have a categorical variable called <code>grades</code> which indicates if the primary school is from Kindergarden to 6th grade, or from Kindergarden to 8th grade. We can use OLS regression to model the relationship between this categorical variable and the math score variable. But first, let’s look at some summary statistics and plots from the two levels of this categorical variable to get a sense of the relationship between this variable and math scores.</p>
<section id="math-scores-by-different-types-of-primary-schools" class="level2">
<h2 class="anchored" data-anchor-id="math-scores-by-different-types-of-primary-schools">Math Scores by Different Types of Primary Schools</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Distributions of math scores for the two types of primary schools</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> math, <span class="at">fill =</span> grades)) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Density Plot of Math Scores by Type of Primary School"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Math Test Score"</span>, <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"lightblue"</span>, <span class="st">"salmon"</span>),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">name =</span> <span class="st">"Type of Primary School"</span>,</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"K-6"</span>, <span class="st">"K-8"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot above, it seems that schools with grades K-6 have slightly higher math scores, on average, than schools with grades K-8. However, there seems to be substantial variability of math scores within each type of school, and there is also a lot of overlap in the distribution of math scores between the two types of schools. Note that using <code>geom_density</code> as opposed to <code>stat_summary</code> or <code>geom_bar</code> allows us to better appreciate within group variability and between group overlap, which is important for understanding the relationship between the predictor variable and the outcome variable.</p>
<p>Let’s also take a look at the means and standard deviations of math scores for the two types of schools:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># means and standard deviations of math scores for the two types of schools</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grades) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_math =</span> <span class="fu">mean</span>(math), <span class="at">sd_math =</span> <span class="fu">sd</span>(math)) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">caption =</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Means and Standard Deviations of Math Scores for K-6 vs K-8 Schools"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">col.names =</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">c</span>(<span class="st">"Type of Primary School"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"Mean Math Score"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                   <span class="st">"SD of Math Score"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Means and Standard Deviations of Math Scores for K-6 vs K-8 Schools</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Type of Primary School</th>
<th style="text-align: right;">Mean Math Score</th>
<th style="text-align: right;">SD of Math Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">KK-06</td>
<td style="text-align: right;">661.0754</td>
<td style="text-align: right;">19.38324</td>
</tr>
<tr class="even">
<td style="text-align: left;">KK-08</td>
<td style="text-align: right;">652.0287</td>
<td style="text-align: right;">18.35107</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We can also directly calculate the difference in means between the two types of schools:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-06"</span>]) <span class="sc">-</span> <span class="fu">mean</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-08"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.046718</code></pre>
</div>
</div>
<p>As such, the plots and summary statistics above provide nice <strong>descriptive</strong> information about the relationship between the type of primary school and math scores. A first pass at some <strong>inference</strong> about this relationship could be made by conducting a t-test:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test for difference in math scores between K-6 and K-8 schools</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(math <span class="sc">~</span> grades, <span class="at">data =</span> CASchools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  math by grades
t = 3.3958, df = 79.359, p-value = 0.001071
alternative hypothesis: true difference in means between group KK-06 and group KK-08 is not equal to 0
95 percent confidence interval:
  3.744404 14.349032
sample estimates:
mean in group KK-06 mean in group KK-08 
           661.0754            652.0287 </code></pre>
</div>
</div>
<p>Given the large t-value and small p-value, we can infer that there is a significant difference in math scores between K-6 and K-8 schools at the population level. Specifically, since the mean math score for K-6 schools is higher than the mean math score for K-8 schools, we can infer that <strong>K-6 schools have higher math scores than K-8 schools at the population level.</strong></p>
<p>As expected, the means for each group from the output from <code>t.test</code> match the means we calculated manually above. The t-statistic from above can also be recovered from the means and standard deviations of the two groups using the following formula:</p>
<p><span class="math display">\[
t = \frac{\bar{X}_1 - \bar{X}_2}{\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}}
\]</span></p>
<p>Calculated as such:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>t_recovered <span class="ot">&lt;-</span> (</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-06"</span>]) <span class="sc">-</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-08"</span>])</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">/</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sqrt</span>(</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sd</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-06"</span>])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">length</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-06"</span>]) <span class="sc">+</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sd</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-08"</span>])<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">length</span>(CASchools<span class="sc">$</span>math[CASchools<span class="sc">$</span>grades <span class="sc">==</span> <span class="st">"KK-08"</span>])</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>t_recovered</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.395833</code></pre>
</div>
</div>
<p>This is exactly what we got from the <code>t.test</code> output!</p>
<p>But how does this relate to OLS regression? First, we can actually replot the relationships between school type and math scores using a scatterplot, where the x-axis is the type of school and the y-axis is the math score. We can even add a line of best fit to this scatterplot by connecting the mean math score for K-6 schools and the mean math score for K-8 schools. An easy way to visualize this line is by using <code>stat_summary</code> to plot the mean math score for each type of school, and then connecting these two points with a line:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># scatterplot of math scores by type of school with line connecting group means</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># and with grades releveled so that the lower mean group is on the left and the # higher mean group is on the right</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>CASchools <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grades =</span> <span class="fu">factor</span>(grades, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"KK-08"</span>, <span class="st">"KK-06"</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> grades, <span class="at">y =</span> math)) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Math Scores by Type of Primary School"</span>,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Type of Primary School"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Math Test Score"</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"K-8"</span>, <span class="st">"K-6"</span>)) <span class="sc">+</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="olsregression_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot above, we can see that the line connecting the mean math scores for K-6 and K-8 schools has a positive slope, which indicates that K-6 schools have higher math scores than K-8 schools. This matches what we saw from the density plots, summary statistics, and t-test output from earlier.</p>
<p>Let’s now fit the OLS regression model to this data, and see how the results relate to the t-test results from earlier and the line above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fitting OLS regression model with the categorical predictor variable,</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># again releveling the grades variable so that the lower mean group is the # reference group</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>model_math_grades <span class="ot">&lt;-</span> <span class="fu">lm</span>(math <span class="sc">~</span> <span class="fu">relevel</span>(grades, <span class="at">ref =</span> <span class="st">"KK-08"</span>),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> CASchools)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_math_grades)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = math ~ relevel(grades, ref = "KK-08"), data = CASchools)

Residuals:
    Min      1Q  Median      3Q     Max 
-47.675 -13.754  -0.479  12.096  57.471 

Coefficients:
                                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         652.0287     0.9765 667.693  &lt; 2e-16 ***
relevel(grades, ref = "KK-08")KK-06   9.0467     2.5624   3.531 0.000461 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.5 on 418 degrees of freedom
Multiple R-squared:  0.02896,   Adjusted R-squared:  0.02663 
F-statistic: 12.46 on 1 and 418 DF,  p-value: 0.0004608</code></pre>
</div>
</div>
<p>There are a few key things to note from the above output. First, the estimated intercept is about 652.028, which <strong>is exactly the mean math score for the reference group (i.e., K-8 schools).</strong> Second, the estimated slope is 9.047, and this <strong>is exactly the difference in means between K-6 and K-8 schools that we calculated manually above and that we also got from the t-test output.</strong> That is, the estimated <strong>slope</strong> represents the <strong>expected change in math score for K-6 schools compared to K-8 schools,</strong> which is simply the difference in means between the two groups.</p>
<p>Like with the OLS regression model we fit earlier with the continuous variables, we obtain a t-value and p-value for the coefficients in this model that we can use for <strong>inference</strong> to the population level. The t-value for the slope is large and the p-value is very small (p &lt; .001), which suggests that there is a significant difference in math scores between K-6 and K-8 schools at the population level. This can also be interpreted in terms of the slope of the line that connects the means between the two groups: <strong>since the p-value for the slope is very small, we can infer that the slope of the line connecting the means between K-6 and K-8 schools is significantly different from 0 at the population level.</strong> Since the slope is positive, we can also infer that K-6 schools have higher math scores than K-8 schools at the population level.</p>
<p>Importantly, the t-value and p-value for the slope in this regression model <strong>is not the exact same as the t-value and p-value from the t-test output</strong>, despite them both being tests on if the difference-in-means (i.e., slope) is different from zero. This is because the t-test output uses a different formula to calculate the standard error of the difference in means than the formula used to calculate the standard error of the slope in the regression model. Specifically, the t-test output uses the formula for the standard error of the difference in means that does not assume equal variances between the two groups, while the regression model uses the formula for the standard error of the slope that does assume equal variances between the two groups.</p>
<p>To get the exact same t-value and p-value as the OLS regression model, we can specify in the <code>t.test</code> formula that <strong>the variances of the two groups are equal,</strong>, so it will then use the same formula for the standard error as the OLS regression model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># t-test for difference in math scores between K-6 and K-8 schools with equal variances</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(math <span class="sc">~</span> grades, <span class="at">data =</span> CASchools, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  math by grades
t = 3.5305, df = 418, p-value = 0.0004608
alternative hypothesis: true difference in means between group KK-06 and group KK-08 is not equal to 0
95 percent confidence interval:
  4.009895 14.083541
sample estimates:
mean in group KK-06 mean in group KK-08 
           661.0754            652.0287 </code></pre>
</div>
</div>
<p>And now we have the exact same standard error, t-value, and p-value as the OLS regression model!</p>
</section>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple Linear Regression</h1>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-burant2022autoregressive" class="csl-entry" role="listitem">
Burant, Christopher J. 2022. <span>“A Methodological Note: An Introduction to Autoregressive Models.”</span> <em>International Journal of Aging &amp; Human Development</em> 95 (4): 516–22. <a href="https://doi.org/10.1177/00914150211066554">https://doi.org/10.1177/00914150211066554</a>.
</div>
<div id="ref-lmtest_bptest" class="csl-entry" role="listitem">
Hothorn, Torsten, Achim Zeileis, Giovanni Millo, and David Mitchell. 2024a. <em>Breusch-Pagan Test</em>. <a href="https://search.r-project.org/CRAN/refmans/lmtest/html/bptest.html">https://search.r-project.org/CRAN/refmans/lmtest/html/bptest.html</a>.
</div>
<div id="ref-lmtest_dwtest" class="csl-entry" role="listitem">
———. 2024b. <em>Durbin-Watson Test</em>. <a href="https://search.r-project.org/CRAN/refmans/lmtest/html/dwtest.html">https://search.r-project.org/CRAN/refmans/lmtest/html/dwtest.html</a>.
</div>
<div id="ref-AER" class="csl-entry" role="listitem">
Kleiber, Christian, and Achim Zeileis. 2026. <em>AER: Applied Econometrics with r</em>. <a href="https://doi.org/10.32614/CRAN.package.AER">https://doi.org/10.32614/CRAN.package.AER</a>.
</div>
<div id="ref-montgomery2021introduction" class="csl-entry" role="listitem">
Montgomery, Douglas C, Elizabeth A Peck, and G Geoffrey Vining. 2021. <em>Introduction to Linear Regression Analysis</em>. John Wiley &amp; Sons.
</div>
<div id="ref-thompson2017vif" class="csl-entry" role="listitem">
Thompson, Christopher G., Rae Seon Kim, Ariel M. Aloe, and Betsy Jane Becker. 2017. <span>“Extracting the Variance Inflation Factor and Other Multicollinearity Diagnostics from Typical Regression Results.”</span> <em>Basic and Applied Social Psychology</em> 39 (2): 81–90. <a href="https://doi.org/10.1080/01973533.2016.1277529">https://doi.org/10.1080/01973533.2016.1277529</a>.
</div>
<div id="ref-whitestrap_white_test" class="csl-entry" role="listitem">
<em>White’s Test</em>. 2019. <a href="https://www.rdocumentation.org/packages/whitestrap/versions/0.0.1/topics/white_test">https://www.rdocumentation.org/packages/whitestrap/versions/0.0.1/topics/white_test</a>.
</div>
<div id="ref-zeileis2020sandwich" class="csl-entry" role="listitem">
Zeileis, Achim, Susanne Köll, and Nathaniel Graham. 2020. <span>“Various Versatile Variances: An Object-Oriented Implementation of Clustered Covariances in r.”</span> <em>Journal of Statistical Software</em> 95 (1): 1–36. <a href="https://doi.org/10.18637/jss.v095.i01">https://doi.org/10.18637/jss.v095.i01</a>.
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>